version: "3.9"
services:
  backend:
    image: "moit03/moit:latest"
    ports:
      - "80:8080"
    restart: "always"
    volumes:
      - '/var/log:/log'

  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node_exporter
    command:
      - '--path.rootfs=/host'
    network_mode: host
    pid: host
    restart: unless-stopped
    volumes:
      - '/:/host:ro,rslave'

#  promtail:
#    image: grafana/promtail:latest
#    volumes:
#      - /etc/promtail/promtail.yml:/etc/promtail/promtail.yml  # 호스트 시스템의 설정 파일을 컨테이너 내부에 마운트
#    command: -config.file=/etc/promtail/promtail.yml
#    ports:
#      - "9080:9080"  # Promtail HTTP endpoint
#    restart: unless-stopped