name: beans-docker

on:
  push:
    branches: [ "feat/logging" ]

jobs:
  CI-CD:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # gradle caching - 빌드 시간 향상
      - name: Gradle Caching
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

#      - name: make env.properties
#        if: |
#          contains(github.ref, 'main') ||
#          contains(github.ref, 'dev')
#        run: |
#          touch env.properties
#          echo "${{ secrets.ENV_PROPERTIES }}" > env.properties
#        shell: bash

      - name: make application-dev
        if: |
          contains(github.ref, 'main') ||
          contains(github.ref, 'dev')
        run: |
          mkdir -p src/main/resources
          cd ./src/main/resources
          touch ./application-dev.properties
          echo "${{ secrets.APPLICATION_DEV }}" > ./application-dev.properties
        shell: bash

      - name: Build with Gradle
        run: ./gradlew build -x test

      # docker build & push
      # Dockerfile을 통해 이미지화
      # push to docker hub
      - name: Docker build & push to dev
        #        if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
        if: |
          contains(github.ref, 'main') ||
          contains(github.ref, 'dev') &&
          github.event.pull_request.merged == true
        run: |
          docker login -u ${{ secrets.DOCKER_EMAIL }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -t ${{ secrets.DOCKER_USERNAME }}/moit . 
          docker push ${{ secrets.DOCKER_USERNAME }}/moit
